### ISSUE TITLE
Break Control Package in Sublime Text 3 

### ISSUE THREAD

**Issue by troymaclure** [mottosso/PersistentPython#4]
After installing on OSX (high sierra), Package Control auto completion doesn't show up anymore in Palette, making impossible to disable the plugin or do whatever related to Package Control, with the exception of changing the user setting file.

You have to remove it manually from the folder "Installed Package" to get Package Control again.

**Comment by stephanepiriou** [comment]
Correction :
On  fresh install, removing manually the package is enough to get Package Control Back.
On an "old" install, it breaks definitively Package Control.
:shit:

**Comment by stephanepiriou** [comment]
Correction 2:
I
